apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ultimate-finch-nodejs 
  janus-idp.io/tekton: ultimate-finch-nodejs
  backstage.io/kubernetes-id: ultimate-finch-nodejs
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: ultimate-finch-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  